export { default as Header } from './header/Header';
export { default as Main } from './main/Main';
export { default as SearchInput } from './search-input/SearchInput';
export { default as Button } from './button/Button';
export { default as ErrorPage } from './error-page/ErrorPage';
export { default as Card } from './card/Card';
export { default as Details } from './details/Details';
export { default as Pagination } from './pagination/Pagination';
export { default as DetailsTemplate } from './details-template/DetailsTemplate';
